global:
  resolve_timeout: 5m

route:
  receiver: salonai-local
  group_by:
    - alertname
    - severity
    - service

  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h

  routes:
    - receiver: salonai-critical
      matchers:
        - severity="critical"
      repeat_interval: 1h

    - receiver: salonai-warning
      matchers:
        - severity="warning"
      repeat_interval: 4h

inhibit_rules:
  - source_matchers:
      - severity="critical"

    target_matchers:
      - severity="warning"

    equal:
      - alertname
      - service

receivers:
  - name: salonai-local

  - name: salonai-critical

  - name: salonai-warning