apiVersion: 1

prune: false

deleteDatasources:
  - name: Tempo
    orgId: 1

datasources:
  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: false
    editable: false

    jsonData:
      httpMethod: GET

      tracesToLogsV2:
        datasourceUid: loki
        spanStartTimeShift: -5m
        spanEndTimeShift: 5m
        filterByTraceID: false
        filterBySpanID: false
        customQuery: true
        query: '{application="salonai"} |~ "$${__trace.traceId}"'

      nodeGraph:
        enabled: true

      search:
        hide: false
